; G-Code generated by Matthew Upp
; WiFi SSID & Password for the MP Mini Delta
; 
; Look below and replace "SSID" with the name of your WiFi network - don't leave spaces after the SSID name
; Look below and replace "PASSWORD" with the password for your WiFi network - don't leave spaces after the password
; This method will not work if WiFi password contains a semicolon “;”
; This method will not work for configuring open system WiFi networks with no password
; Lines with only a semicolon are for making line separations only
; Please add a blank line to the end of the file while editing. DokuWiki Code Blocks deletes blank lines at the end of the block but g-code files should end with a single blank line at the end.
; 
; 
M106 S1 ; turn fan off in case it was already on
M106 S240 ; turn fan on to signify start
G28 ; home all axes
; 
;  
M550 <<INSERT NETWORK ESSID>>
M551 <<THE WIFI PASSWORD>>
; 
; 
G28 ; re-home all axes
M106 S1 ; turn fan off to signify completion
M84 ; disable motors
